About Us Page
johnperry99/INFOX pull request #17
Opened 2021-12-29 20:43 UTC by johnperry99

- Create frontend for About Us page
- Added ButtonLink for AboutUs component to AppHeader.jsx
- Added route for AboutUs in App.js

2021-12-29 21:05 UTC, johnsoncv approved these changes
lgtm

2021-12-29 21:22 UTC, johnsoncv requested changes

2021-12-29 21:22 UTC, johnsoncv commented on client/src/AboutUs.jsx
> +                    ollaboration and coordination in open-source and variant-rich software development.
typo  
ollaboration -> collaboration

2021-12-30 10:38 UTC, LaithHanania requested changes

2021-12-30 10:38 UTC, LaithHanania commented on client/src/AboutUs.jsx
> +                    ollaboration and coordination in open-source and variant-rich software development.
good catch

2021-12-30 10:38 UTC, LaithHanania commented on client/src/AboutUs.jsx
> +            <Card sx={{ padding: 2, marginBottom: 1, marginTop: 1, width: 95 + "%" }}>
for width I think you can do "95%" instead of 95 + %

2021-12-30 10:38 UTC, LaithHanania commented on client/src/AboutUs.jsx
> +            <Card sx={{ padding: 2, marginBottom: 1, width: 95 + "%" }}>
width: "95%"

2021-12-30 10:38 UTC, LaithHanania commented on client/src/AboutUs.jsx
> +            <Card sx={{ padding: 2, width: 95 + "%" }}>
width: "95%"

2021-12-30 10:38 UTC, LaithHanania commented on client/src/AboutUs.jsx
> +            <Card sx={{display:"flex", marginTop:1, width:50+"%", justifyContent:"space-evenly"}}>
width: "50%"

2021-12-30 16:47 UTC, LaithHanania approved these changes
Looks good!

2021-12-30 16:49 UTC, johnperry99 commented on client/src/AboutUs.jsx
> +                    ollaboration and coordination in open-source and variant-rich software development.
Resolved

2021-12-30 17:01 UTC, johnsoncv approved these changes

2021-12-30 17:02 UTC, merged